const VERSION='5.6';
const clean=s=>String(s??'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#x27;/g,"'").replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const host=u=>{try{return new URL(u).hostname.replace(/^www\./,'').toLowerCase()}catch{return ''}};
const blocked=/^(bing\.com|google\.(com|co\.[a-z]{2}|[a-z]{2})|duckduckgo\.com|search\.yahoo\.com|yahoo\.com|r\.jina\.ai|copilot\.microsoft\.com)$/i;
const bad=/wikipedia|tripadvisor|booking\.com|expedia|agoda|kayak|skyscanner|facebook|instagram|youtube|reddit|pinterest|tiktok|news|blog|forum|medium\.com/i;
function unwrap(u){try{const z=new URL(u);for(const k of ['u','uddg','url']){const v=z.searchParams.get(k);if(v){try{return decodeURIComponent(v)}catch{return v}}}return u}catch{return u}}
function classify(q){const t=norm(q);if(/\bdmc\b|destination management|ground handling|ground operator|inbound operator|incoming operator|travel supplier/.test(t))return 'SUPPLIER';if(/hotel|resort|accommodation|suite|villa/.test(t))return 'HOTEL';if(/flight|airline|fare|ticket/.test(t))return 'FLIGHT';if(/job|vacancy|career|hiring|employment|position/.test(t))return 'JOB';if(/activity|excursion|attraction|ski|tour/.test(t))return 'ACTIVITY';return 'GENERAL'}
const knownDestinations=['Sri Lanka','Spain','Turkey','Türkiye','Georgia','Russia','Japan','Azerbaijan','Vietnam','Bosnia','Thailand','Costa Rica','Czech Republic','Czechia','Prague','UAE','United Arab Emirates','Maldives','Indonesia','Malaysia','Egypt','Saudi Arabia','Portugal','France','Italy','Greece','Germany','Austria','Switzerland','Morocco','Oman','Qatar','Bahrain','Kuwait'];
function destination(q){const t=String(q);for(const d of knownDestinations){const re=new RegExp(`\\b${d.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\\\$&')}\\b`,'i');if(re.test(t))return d}const patterns=[/\b(?:in|around|near|at)\s+([^,.!?]+?)(?=\s+(?:for|with|that|who|offering|providing|under|from|to|and|suitable)\b|$)/i,/\b(?:for|to)\s+([^,.!?]+?)\s+(?:travel|trip|tour|holiday|destination|suppliers?|hotels?|activities?|jobs?)\b/i];for(const p of patterns){const m=t.match(p);if(m&&m[1].trim().length>1)return m[1].trim()}return ''}
function aliases(d){const x=norm(d);const a={turkey:['turkiye'],türkiye:['turkey'],czechia:['czech republic'],prague:['praha','czech republic'],uae:['united arab emirates'],usa:['united states','united states of america'],uk:['united kingdom','great britain'],vietnam:['viet nam'],russia:['russian federation'],sri:['sri lanka'],sri_lanka:['sri lanka'],srilanka:['sri lanka'],spain:['espana','españa']};return [...new Set([x,...(a[x]||[])])].map(norm)}
function matchesDestination(s,d){if(!d)return true;const x=norm(s);return aliases(d).some(a=>a.length>2&&x.includes(a))}
function queries(task,type,d){if(type==='SUPPLIER')return [...new Set([`${d} DMC B2B travel agency`,`"${d}" "destination management company" "travel agents"`,`"${d}" "ground handling" "tour operator"`,`"${d}" "inbound tour operator" B2B`,`"${d}" DMC "travel trade" partner`,`"${d}" DMC partner net rates`])];if(type==='HOTEL')return [...new Set([task,`${d} hotel official website breakfast family`,`${d} 4 star hotels central official`])];if(type==='JOB')return [...new Set([task,`${task} official careers`,`${task} employer jobs`])];return [...new Set([task,`${d||task} official`,`${d||task} services providers`])].slice(0,6)}
async function get(url,ms=7500){const c=new AbortController();const timer=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; AlyOmegaResearch/5.6)','Accept':'text/html,application/xml,text/plain;q=.8,*/*;q=.5','Accept-Language':'en-US,en;q=.9'}});return{ok:r.ok,status:r.status,text:await r.text()}}catch(e){return{ok:false,status:0,text:'',error:e?.name==='AbortError'?'TIMEOUT':String(e?.message||e)}}finally{clearTimeout(timer)}}
function parseRss(h){const out=[];const re=/<item>([\s\S]*?)<\/item>/gi;let m;while((m=re.exec(h))&&out.length<60){const b=m[1],u=b.match(/<link>([\s\S]*?)<\/link>/i),t=b.match(/<title>([\s\S]*?)<\/title>/i),d=b.match(/<description>([\s\S]*?)<\/description>/i);if(u&&t)out.push({url:unwrap(clean(u[1])),title:clean(t[1]),snippet:d?clean(d[1]):''})}return out}
function parseLinks(h){const out=[];const re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(h))&&out.length<120){const u=unwrap(m[1]),t=clean(m[2]);if(/^https?:\/\//i.test(u)&&t.length>2)out.push({url:u,title:t,snippet:''})}return out}
function parseBing(h){const out=[];const re=/<li[^>]*class=["'][^"']*b_algo[^"']*["'][\s\S]*?<h2[\s\S]*?<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>[\s\S]*?(?:<p>([\s\S]*?)<\/p>)?[\s\S]*?<\/li>/gi;let m;while((m=re.exec(h))&&out.length<60)out.push({url:unwrap(clean(m[1])),title:clean(m[2]),snippet:clean(m[3]||'')});return out.length?out:parseLinks(h)}
function parseJina(h){const out=[];const re=/\[([^\]]{2,220})\]\((https?:\/\/[^)\s]+)[^)]*\)/g;let m;while((m=re.exec(h))&&out.length<100){const title=clean(m[1]);const url=unwrap(m[2]);if(title&&url)out.push({url,title,snippet:''})}return out}
function candidate(c){const u=unwrap(c.url),h=host(u);return /^https?:\/\//i.test(u)&&h&&!blocked.test(h)&&!bad.test(`${u} ${c.title||''}`)}
function signals(c,type,d,body=''){const p=norm(`${c.title} ${c.snippet} ${c.url} ${body}`);return{destination:matchesDestination(p,d),supplier:/\bdmc\b|destination management|ground handling|ground operator|inbound operator|incoming operator|travel agency|tour operator|travel services|destination specialist/.test(p),hotel:/hotel|resort|rooms?|suite|villa|accommodation/.test(p),service:/hotel booking|accommodation|airport transfer|airport transfers|transport|tour|excursion|guided tour|sightseeing|packages|itinerar|meet and greet|family|groups?|fit travel/.test(p),trade:/\bb2b\b|travel trade|travel agent|tour operator|wholesale|agents worldwide|partners worldwide|trade only|for agents|for tour operators|business partners|net rate|contract|contracting|white label|partner program|wholesale rate|commission|agent rates|b2b rates|trade rates|overseas agents|international travel professionals/.test(p),official:/official|contact|about|services|booking|accommodation|careers|company|partner/.test(p),contact:/\b(?:email|e-mail|phone|tel|telephone|whatsapp|contact us)\b|@[a-z0-9.-]+\.[a-z]{2,}/.test(p),saudi:/saudi|ksa|arabia|riyadh|jeddah|makkah|mecca|madinah|gcc|gulf/.test(p),groups:/groups?|famil|honeymoon|corporate|mice|umrah/.test(p),transport:/airport transfer|airport transfers|transport|chauffeur|private transfer|vehicle/.test(p),accommodation:/hotel|resort|rooms?|villa|accommodation|lodging/.test(p),bad:bad.test(`${c.url} ${c.title}`)}}
function score(c,type,d,body=''){const s=signals(c,type,d,body);if(s.bad||!s.destination)return -200;let n=30;if(type==='SUPPLIER'){if(!s.supplier)return 4;n+=35;if(s.trade)n+=30;if(s.service)n+=20;if(s.contact)n+=5;if(s.saudi)n+=5;if(s.groups)n+=3}else if(type==='HOTEL'){if(!s.hotel)return 4;n+=35;if(s.service)n+=20;if(s.contact)n+=5}else{if(s.service)n+=25;if(s.official)n+=10}return n}
function reason(c,type,d,body=''){const s=signals(c,type,d,body);if(s.bad)return 'Rejected non-target source';if(!s.destination)return 'Destination not evidenced';if(type==='SUPPLIER'&&!s.supplier)return 'Supplier identity not evidenced';if(type==='HOTEL'&&!s.hotel)return 'Hotel identity not evidenced';if(type==='SUPPLIER'&&!s.trade)return 'Supplier found but B2B/trade evidence is not visible';if(type==='SUPPLIER'&&!s.service)return 'Supplier identity found but service capability is not visible';return 'Live page evidence supports destination and business relevance'}
function extractEvidence(c,type,d,body=''){const raw=clean(body);const p=norm(raw);const s=signals(c,type,d,body);const pick=(rx,max=260)=>{const m=raw.match(rx);return m?clean(m[0]).slice(0,max):''};const serviceTerms=[];if(s.accommodation)serviceTerms.push('Accommodation');if(s.transport)serviceTerms.push('Transfers/transport');if(/tour|excursion|sightseeing|itinerar|packages/.test(p))serviceTerms.push('Tours/excursions');if(s.groups)serviceTerms.push('Groups/family/occasion travel');if(/mice|corporate/.test(p))serviceTerms.push('Corporate/MICE');const b2b=pick(/[^.]{0,110}(?:b2b|travel trade|travel agents?|tour operators?|wholesale|net rates?|partner program|business partners|contracting)[^.]{0,180}/i);const dest=pick(new RegExp(`[^.]{0,100}(?:${aliases(d).join('|')})[^.]{0,180}`,'i'));const contact=pick(/[^.]{0,80}(?:email|e-mail|phone|tel|telephone|whatsapp|contact us)[^.]{0,160}/i);const saudi=pick(/[^.]{0,100}(?:saudi|ksa|riyadh|jeddah|makkah|mecca|madinah|gcc|gulf)[^.]{0,180}/i);const snippets=[b2b,dest,contact,saudi].filter(Boolean);const evidenceQuote=(snippets[0]||snippets[1]||raw.slice(0,260)).slice(0,320);const confidence=Math.min(99,45+(s.destination?15:0)+(s.supplier||s.hotel?15:0)+(s.service?10:0)+(s.trade?10:0)+(s.contact?2:0)+(s.saudi?3:0));let validation='NEEDS_VERIFICATION';if(type==='SUPPLIER'&&s.destination&&s.supplier&&s.service&&s.trade)validation=confidence>=85?'VERIFIED_B2B':'QUALIFIED_B2B';else if(s.destination&&(s.supplier||s.hotel)&&s.service)validation='PARTIALLY_VERIFIED';return{business_type:type==='SUPPLIER'?'DMC / Travel Supplier':type==='HOTEL'?'Hotel / Accommodation':type,services:serviceTerms,b2b_evidence:b2b||'',destination_evidence:dest||'',saudi_relevance:saudi||'No Saudi/KSA-specific evidence found on inspected page',contact_evidence:contact||'',evidence_quote:evidenceQuote,evidence_points:snippets,confidence,validation}}
async function inspect(c){let z=await get(c.url,6500);if(z.ok&&z.text.length>400)return clean(z.text).slice(0,30000);z=await get(`https://r.jina.ai/${c.url}`,7000);return z.ok?clean(z.text).slice(0,30000):''}
async function provider(name,url,parser,query,diag){const z=await get(url,9000);diag.push({provider:name,query,status:z.status,bytes:z.text.length,error:z.error||null});return z.ok?parser(z.text).map(x=>({...x,query,provider:name})).filter(candidate):[]}
const seedMap={'sri lanka':[['Travelo DMC','https://www.travelodmc.com/'],['Yatours','https://www.yatours.com/travel-agent-partnerships'],['Zelenso Travel','https://zelenso.com/travel-trade'],['Lakpura','https://www.lakpura.com/pages/agents'],['Total Sri Lanka DMC','https://www.totalsrilankadmc.com/'],['Lanka Travel Gateway','https://www.lankatravelgateway.com/partner-with-us'],['Travelorphic','https://travelorphic.com/'],['Delft Tours','https://delfttours.com/b2b-partnerships'],['Zephyra Travels','https://www.zephyratravels.com/partners'],['Resfeber Holidays','https://resfeberholidays.com/']],
'spain':[['Optima Deluxe Travel Management','https://optima-travel.com/en/'],['LAMER Turismo','https://www.lamerturismo.com/'],['Guest Incoming','https://www.guestincoming.com/'],['Odisea Tours','https://odisea-tours.com/spain-dmc'],['Andromeda Viajes DMC','https://andromedaviajesdmc.com/'],['Iberinbound Travel','https://iberinbound.com/'],['Inbound Spain','https://inboundspain.com/travel-partners/'],['Welcome to Spain DMC & MICE','https://www.welcometospain.es/'],['SpainTop','https://spaintop.com/faq-travel-trade-and-partnerships.html'],['HCG UK & Europe DMC','https://www.hcgukeuropedmc.com/destination/spain-dmc.html']]};
function seeds(d){const k=norm(d);for(const key of Object.keys(seedMap))if(k===key||k.includes(key)||key.includes(k))return seedMap[key].map(([title,url])=>({title,url,snippet:'Seed candidate; requires live page verification',provider:'verified-seed'}));return []}
async function research(task){const type=classify(task),d=destination(task),qs=queries(task,type,d),diag=[],all=[];for(const q of qs){const e=encodeURIComponent(q);const providers=[['Bing RSS',`https://www.bing.com/search?format=rss&q=${e}`,parseRss],['Bing HTML',`https://www.bing.com/search?q=${e}&count=20`,parseBing],['DuckDuckGo HTML',`https://html.duckduckgo.com/html/?q=${e}`,parseLinks],['Jina Google',`https://r.jina.ai/https://www.google.com/search?q=${e}`,parseJina],['Jina Bing',`https://r.jina.ai/https://www.bing.com/search?q=${e}`,parseJina]];const batches=await Promise.all(providers.map(p=>provider(p[0],p[1],p[2],q,diag)));for(const b of batches)all.push(...b)}
const sourcePool=all.length?all:seeds(d);const byDomain=new Map();for(const c of sourcePool){const h=host(c.url);if(!h||blocked.test(h))continue;const prev=byDomain.get(h);if(!prev||score(c,type,d)>score(prev,type,d))byDomain.set(h,c)}
let unique=[...byDomain.values()];if(unique.length<10){for(const c of seeds(d)){const h=host(c.url);if(h&&!byDomain.has(h)){byDomain.set(h,c);unique.push(c)}}}
const pre=unique.map(c=>({...c,search_score:score(c,type,d)})).sort((a,b)=>b.search_score-a.search_score).slice(0,18);const inspected=await Promise.all(pre.map(async c=>{const body=await inspect(c);return{...c,body,page_score:score(c,type,d,body),page_reason:reason(c,type,d,body),evidence:extractEvidence(c,type,d,body)}}));
const threshold=type==='SUPPLIER'?55:25;const ranked=inspected.filter(c=>c.page_score>=threshold).sort((a,b)=>b.page_score-a.page_score).slice(0,10);const results=ranked.map((c,i)=>({rank:i+1,name:c.title||host(c.url),title:c.title||host(c.url),domain:host(c.url),url:c.url,snippet:c.snippet||c.page_reason,description:c.page_reason,search_score:c.search_score,page_score:c.page_score,validation:c.evidence.validation,reason:c.page_reason,signals:signals(c,type,d,c.body),evidence:c.evidence,b2b_evidence:c.evidence.b2b_evidence,services:c.evidence.services,saudi_relevance:c.evidence.saudi_relevance,contact:c.evidence.contact_evidence,evidence_quote:c.evidence.evidence_quote,confidence:c.evidence.confidence}));
return{ok:true,version:VERSION,brain:'Aly Omega Research Core',task,intent:type,destination:d,search_queries:qs,providers:[...new Set(diag.map(x=>x.provider))],diagnostics:diag,stats:{discovered:all.length,unique_domains:unique.length,inspected:inspected.length,ranked:ranked.length,returned:results.length,rejected:inspected.filter(c=>c.page_score<threshold).length,deep_evidence:results.filter(c=>c.evidence.evidence_quote).length,qualified_b2b:results.filter(c=>c.evidence.validation==='VERIFIED_B2B'||c.evidence.validation==='QUALIFIED_B2B').length},results,contract:{goal:'Real Internet research first; page evidence before release',rule:'Search queries are instructions, never evidence',release_rule:'Supplier candidates need destination + entity identity + visible service + B2B/trade evidence',evidence_rule:'Every released supplier includes inspectable evidence fields, confidence and validation state',seed_rule:'Fallback seeds are never released without live page inspection',next:'Evaluation → Validation Gate → Red Team → Final Synthesis'}}}
export default async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return res.status(204).end();try{let task='';if(req.method==='GET')task=String(req.query?.task||'').trim();else{let body=req.body;if(typeof body==='string'){try{body=JSON.parse(body)}catch{body={}}}task=String(body?.task||'').trim()}if(!task)return res.status(400).json({ok:false,error:'task is required',version:VERSION});return res.status(200).json(await research(task))}catch(e){return res.status(500).json({ok:false,error:String(e?.message||e),version:VERSION})}}