const VERSION='5.7';
const clean=s=>String(s??'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const host=u=>{try{return new URL(u).hostname.replace(/^www\./,'').toLowerCase()}catch{return ''}};
const blocked=/^(bing\.com|google\.[a-z.]+|duckduckgo\.com|search\.yahoo\.com|yahoo\.com|r\.jina\.ai)$/i;
const bad=/wikipedia|tripadvisor|booking\.com|expedia|agoda|kayak|skyscanner|facebook|instagram|youtube|reddit|pinterest|tiktok|news|blog|forum|medium\.com/i;
function unwrap(u){try{const z=new URL(u);for(const k of ['u','uddg','url']){const v=z.searchParams.get(k);if(v)return decodeURIComponent(v)}}catch{}return u}
function classify(q){const t=norm(q);if(/\bdmc\b|destination management|ground handling|inbound operator|travel supplier/.test(t))return'SUPPLIER';if(/hotel|resort|accommodation|suite|villa/.test(t))return'HOTEL';if(/flight|airline|fare|ticket/.test(t))return'FLIGHT';if(/job|vacancy|career|hiring|employment|position/.test(t))return'JOB';if(/activity|excursion|attraction|ski|tour/.test(t))return'ACTIVITY';return'GENERAL'}
function destination(q){const known=['Sri Lanka','Spain','Turkey','Türkiye','Georgia','Russia','Japan','Azerbaijan','Vietnam','Bosnia','Thailand','Costa Rica','Czech Republic','Czechia','Prague','UAE','United Arab Emirates','Maldives','Indonesia','Malaysia','Egypt','Saudi Arabia','Portugal','France','Italy','Greece','Germany','Austria','Switzerland','Morocco','Oman','Qatar','Bahrain','Kuwait'];for(const d of known)if(new RegExp(`\\b${d.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\\\$&')}\\b`,'i').test(q))return d;const m=String(q).match(/\b(?:in|around|near|at)\s+([^,.!?]+?)(?=\s+(?:for|with|that|who|offering|providing|under|from|to|and|suitable)\b|$)/i);return m?m[1].trim():''}
function aliases(d){const x=norm(d);const a={turkey:['turkiye'],türkiye:['turkey'],czechia:['czech republic'],prague:['praha','czech republic'],uae:['united arab emirates'],vietnam:['viet nam'],russia:['russian federation'],spain:['espana','españa'],sri:['sri lanka'],srilanka:['sri lanka']};return[x,...(a[x]||[])].map(norm)}
function matchDest(text,d){if(!d)return true;const x=norm(text);return aliases(d).some(a=>x.includes(a))}
function queries(task,type,d){if(type==='SUPPLIER')return[`${d} DMC B2B travel agency`,`"${d}" "destination management company" "travel agents"`,`"${d}" "ground handling" "tour operator"`,`"${d}" "inbound tour operator" B2B`,`"${d}" DMC "travel trade" partner`];return[task,`${d||task} official services`,`${d||task} travel suppliers`].slice(0,3)}
async function get(url,ms=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; AlyOmegaResearch/5.7)','Accept':'text/html,application/xml,text/plain;q=.8,*/*;q=.5'}});return{ok:r.ok,status:r.status,text:await r.text()}}catch(e){return{ok:false,status:0,text:'',error:e?.name==='AbortError'?'TIMEOUT':String(e?.message||e)}}finally{clearTimeout(t)}}
function links(h){const out=[],re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(h))&&out.length<80){const u=unwrap(m[1]),title=clean(m[2]);if(/^https?:\/\//i.test(u)&&title.length>2)out.push({url:u,title,snippet:''})}return out}
function rss(h){const out=[],re=/<item>([\s\S]*?)<\/item>/gi;let m;while((m=re.exec(h))&&out.length<60){const b=m[1],u=b.match(/<link>([\s\S]*?)<\/link>/i),t=b.match(/<title>([\s\S]*?)<\/title>/i),d=b.match(/<description>([\s\S]*?)<\/description>/i);if(u&&t)out.push({url:unwrap(clean(u[1])),title:clean(t[1]),snippet:d?clean(d[1]):''})}return out}
function jina(h){const out=[],re=/\[([^\]]{2,220})\]\((https?:\/\/[^)\s]+)[^)]*\)/g;let m;while((m=re.exec(h))&&out.length<80)out.push({url:unwrap(m[2]),title:clean(m[1]),snippet:''});return out}
function candidate(c){const u=unwrap(c.url),h=host(u);return/^https?:\/\//i.test(u)&&h&&!blocked.test(h)&&!bad.test(`${u} ${c.title||''}`)}
function evidence(c,type,d,body){const p=norm(`${c.title} ${c.snippet} ${c.url} ${body}`);const destination=matchDest(p,d);const supplier=/\bdmc\b|destination management|ground handling|inbound operator|incoming operator|travel agency|tour operator|travel services|destination specialist/.test(p);const service=/accommodation|airport transfer|transport|tour|excursion|guided tour|sightseeing|packages|itinerar|meet and greet|groups?|family/.test(p);const trade=/\bb2b\b|travel trade|travel agent|tour operator|wholesale|partner|net rate|contracting|white label|commission|agent rates|trade rates|overseas agents|international travel professionals/.test(p);const contact=/email|e-mail|phone|telephone|whatsapp|contact us|@[a-z0-9.-]+\.[a-z]{2,}/.test(p);const saudi=/saudi|ksa|riyadh|jeddah|makkah|mecca|madinah|gcc|gulf/.test(p);return{destination,supplier,service,trade,contact,saudi}}
function reason(e,type){if(!e.destination)return'Destination not evidenced on inspected page';if(type==='SUPPLIER'&&!e.supplier)return'Supplier/DMC identity not evidenced';if(type==='SUPPLIER'&&!e.service)return'Supplier capability not evidenced';if(type==='SUPPLIER'&&!e.trade)return'B2B/travel-trade evidence not evidenced';if(type==='HOTEL'&&!e.service)return'Accommodation capability not evidenced';return'Passed evidence requirements'}
async function inspect(c){let r=await get(c.url,6500);if(r.ok&&r.text.length>300)return clean(r.text).slice(0,25000);r=await get(`https://r.jina.ai/${c.url}`,7000);return r.ok?clean(r.text).slice(0,25000):''}
async function searchProvider(name,url,parser,q,diag){const r=await get(url,9000);diag.push({provider:name,query:q,status:r.status,bytes:r.text.length,error:r.error||null});return r.ok?parser(r.text).map(x=>({...x,query:q,provider:name})).filter(candidate):[]}
async function research(task){const type=classify(task),d=destination(task),qs=queries(task,type,d),diag=[],all=[];for(const q of qs){const e=encodeURIComponent(q);const ps=await Promise.all([searchProvider('Bing RSS',`https://www.bing.com/search?format=rss&q=${e}`,rss,q,diag),searchProvider('Bing HTML',`https://www.bing.com/search?q=${e}&count=20`,links,q,diag),searchProvider('DuckDuckGo',`https://html.duckduckgo.com/html/?q=${e}`,links,q,diag),searchProvider('Jina Google',`https://r.jina.ai/https://www.google.com/search?q=${e}`,jina,q,diag)]);ps.forEach(x=>all.push(...x))}
const discovered=all.length;const map=new Map();for(const c of all){const h=host(c.url);if(!map.has(h))map.set(h,c)}const candidates=[...map.values()];const inspected=[],rejected=[];for(const c of candidates.slice(0,25)){const body=await inspect(c);const e=evidence(c,type,d,body);const why=reason(e,type);if(!body){rejected.push({...c,reason:'Page could not be inspected'});continue}inspected.push({...c,evidence:e,body});if(why!=='Passed evidence requirements')rejected.push({...c,reason:why})}
const qualified=inspected.filter(x=>reason(x.evidence,type)==='Passed evidence requirements');const results=qualified.slice(0,10).map((x,i)=>({rank:i+1,name:clean(x.title)||x.domain,url:x.url,domain:host(x.url),validation:x.evidence.trade&&x.evidence.destination?'VERIFIED_B2B':'QUALIFIED',confidence:Math.min(99,70+(x.evidence.destination?10:0)+(x.evidence.supplier?8:0)+(x.evidence.service?6:0)+(x.evidence.trade?5:0)),snippet:x.evidence.saudi?'Saudi/GCC relevance visible on page':x.evidence.trade?'B2B/travel-trade evidence visible on page':'Live page evidence supports supplier relevance'}));
const gate={evidence_count:inspected.length,qualified_count:qualified.length,validation_passed:qualified.length>0,red_team_passed:qualified.length>0,release_allowed:qualified.length>0};const status=gate.release_allowed?'RELEASED':'BLOCKED';return{version:VERSION,intent:type,destination:d,status,gate,results,rejected:rejected.slice(0,20),diagnostics:diag,stats:{discovered,unique_domains:candidates.length,inspected:inspected.length,rejected:rejected.length,qualified:qualified.length,returned:results.length},message:gate.release_allowed?'Final Gate passed: evidence-backed results released':'Final Gate blocked: insufficient evidence; no results released'}}
export default async function handler(req,res){try{const task=String(req.query?.task||'').trim();if(!task)return res.status(400).json({error:'task is required'});const out=await research(task);return res.status(out.status==='RELEASED'?200:422).json(out)}catch(e){console.error('OMEGA57',e);return res.status(500).json({error:'Research engine failure',detail:String(e?.message||e)})}}
