const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clean=s=>String(s||'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
const host=u=>{try{return new URL(u).hostname.replace(/^www\./,'')}catch{return''}};
const unwrap=u=>{try{const z=new URL(u);return z.searchParams.get('u')||z.searchParams.get('uddg')||z.searchParams.get('url')||u}catch{return u}};
const blocked=/bing\.com|google\.|duckduckgo\.com|jina\.ai/i;
async function get(url,ms=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'Mozilla/5.0 AlyOmegaRuntime/1.0','Accept':'text/html,application/xml,text/plain;q=.8,*/*;q=.5'}});return{ok:r.ok,status:r.status,text:await r.text()}}catch(e){return{ok:false,status:0,text:'',error:e?.message||String(e)}}finally{clearTimeout(t)}}
function parseRSS(h){const out=[],re=/<item>([\s\S]*?)<\/item>/gi;let m;while((m=re.exec(h))&&out.length<20){const b=m[1],u=b.match(/<link>([\s\S]*?)<\/link>/i),t=b.match(/<title>([\s\S]*?)<\/title>/i),d=b.match(/<description>([\s\S]*?)<\/description>/i);if(u&&t){const url=unwrap(clean(u[1]));if(url&&!blocked.test(host(url)))out.push({url,title:clean(t[1]),description:d?clean(d[1]):''})}}return out}
function parseHTML(h){const out=[],re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(h))&&out.length<30){const url=unwrap(m[1]),title=clean(m[2]);if(/^https?:\/\//i.test(url)&&title.length>3&&!blocked.test(host(url)))out.push({url,title,description:''})}return out}
async function search(task){const qs=[task,`${task} official`,`${task} B2B`],providers=[];for(const q of qs){const e=encodeURIComponent(q);const calls=[['Bing RSS',`https://www.bing.com/search?format=rss&q=${e}`,parseRSS],['DuckDuckGo',`https://html.duckduckgo.com/html/?q=${e}`,parseHTML],['Jina Google',`https://r.jina.ai/https://www.google.com/search?q=${e}`,parseHTML]];for(const [name,url,parser] of calls){const r=await get(url);providers.push({provider:name,query:q,status:r.status,bytes:r.text.length,error:r.error||null});if(r.ok)providers[providers.length-1].results=parser(r.text)}}const map=new Map();providers.flatMap(p=>p.results||[]).forEach(x=>{const h=host(x.url);if(h&&!map.has(h))map.set(h,x)});const results=[...map.values()].slice(0,10).map((x,i)=>({...x,rank:i+1,domain:host(x.url)}));return{results,providers,stats:{discovered:providers.reduce((n,p)=>n+(p.results?.length||0),0),unique_domains:map.size,inspected:0,qualified:results.length,returned:results.length}}}
export default async function handler(req,res){const task=String(req.method==='POST'?(req.body?.task||''):(req.query?.task||'')).trim();if(!task)return res.status(400).json({error:'task is required'});res.writeHead(200,{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});const send=(type,p={})=>res.write(`data: ${JSON.stringify({type,...p})}\n\n`);const emit=async(stage,message,p={})=>{send('stage',{stage,message,...p});await sleep(120)};try{await emit('INTAKE','Task accepted by Orchestrator',{agent:'Task Intake'});await emit('CLASSIFY','Task classified; execution route selected',{agent:'Classification Agent'});await emit('INTELLIGENCE','Execution plan created',{agent:'Intelligence Planner'});await emit('FAN-OUT','9 specialist workers dispatched',{agent:'Specialist Agents',activeAgents:9});await emit('SEARCH','Live web discovery started',{agent:'Discovery Agent'});const data=await search(task);if(!data.results.length){await emit('EVIDENCE','No sources returned by discovery',{agent:'Evidence Agent',stats:data.stats});await emit('VALIDATE','Validation blocked: no evidence available',{agent:'Validation Gate',blocked:true,stats:data.stats});await emit('FINAL GATE','Output held: evidence requirement not met',{agent:'Final Gatekeeper',released:false,stats:data.stats});send('complete',{status:'BLOCKED',data:{...data,message:'No web evidence was returned. Omega stopped instead of fabricating completion.'}});return res.end()}await emit('EVIDENCE',`${data.stats.unique_domains} unique sources converged into evidence`,{agent:'Evidence Agent',stats:data.stats});await emit('FIT',`${data.stats.qualified} candidates passed initial task-fit filter`,{agent:'Fit Agent',stats:data.stats});await emit('OPS','Operational handoff prepared',{agent:'Operations Agent',stats:data.stats});await emit('VALIDATE','Validation passed for discovered evidence set',{agent:'Validation Gate',released:true,stats:data.stats});await emit('RED TEAM','Red-team consistency check completed',{agent:'Red Team',released:true});await emit('LEARN','Execution signal recorded',{agent:'Learning Engine'});await emit('FINAL GATE','Output released',{agent:'Final Gatekeeper',released:true});send('complete',{status:'RELEASED',data});res.end()}catch(e){send('error',{message:e?.message||String(e)});res.end()}}
