function decode(s=''){return s.replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#x27;/g,"'").replace(/&nbsp;/g,' ').replace(/&#([0-9]+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/\s+/g,' ').trim()}
function cleanUrl(u=''){try{return decodeURIComponent(u)}catch{return u}}
function extractBing(html){const out=[];const re=/<li[^>]+class=["']b_algo["'][\s\S]*?<\/li>/gi;let m;while((m=re.exec(html))&&out.length<10){const b=m[0],a=b.match(/<h2>[\s\S]*?<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i),p=b.match(/<p[^>]*>([\s\S]*?)<\/p>/i);if(a)out.push({rank:out.length+1,title:decode(a[2]),url:cleanUrl(a[1]),description:p?decode(p[1]):''})}return out}
function extractDDG(html){const out=[];const re=/<a[^>]+class=["'][^"']*result__a[^"']*["'][^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<10){const title=decode(m[2]);let url=cleanUrl(m[1]);let tail=html.slice(m.index,m.index+1800);const p=tail.match(/class=["'][^"']*result__snippet[^"']*["'][^>]*>([\s\S]*?)<\//i);if(url.includes('uddg=')){try{const u=new URL(url,'https://duckduckgo.com');url=decodeURIComponent(u.searchParams.get('uddg')||url)}catch{}}out.push({rank:out.length+1,title,url,description:p?decode(p[1]):''})}return out}
function extractDDGLite(html){const out=[];const re=/<a[^>]+class=["']result-link["'][^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<10){const tail=html.slice(m.index,m.index+2200),p=tail.match(/class=["']result-snippet["'][^>]*>([\s\S]*?)<\//i);out.push({rank:out.length+1,title:decode(m[2]),url:cleanUrl(m[1]),description:p?decode(p[1]):''})}return out}
async function provider(url,parser){try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36','Accept':'text/html,application/xhtml+xml,text/plain;q=0.8,*/*;q=0.5','Accept-Language':'en-US,en;q=0.9'}});if(!r.ok)return {results:[],status:r.status};const html=await r.text();return {results:parser(html),status:r.status}}catch(e){return {results:[],status:0,error:e.message}}}
export default async function handler(req,res){
 res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');
 if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({error:'POST only'});
 const task=String(req.body?.task||'').trim();if(!task)return res.status(400).json({error:'task is required'});
 const q=encodeURIComponent(task);let results=[],providerName='';const diagnostics=[];
 let r=await provider(`https://www.bing.com/search?q=${q}&count=10`,extractBing);diagnostics.push({provider:'Bing HTML',status:r.status,count:r.results.length});results=r.results;if(results.length)providerName='Bing HTML';
 if(!results.length){r=await provider(`https://html.duckduckgo.com/html/?q=${q}`,extractDDG);diagnostics.push({provider:'DuckDuckGo HTML',status:r.status,count:r.results.length});results=r.results;if(results.length)providerName='DuckDuckGo HTML'}
 if(!results.length){r=await provider(`https://lite.duckduckgo.com/lite/?q=${q}`,extractDDGLite);diagnostics.push({provider:'DuckDuckGo Lite',status:r.status,count:r.results.length});results=r.results;if(results.length)providerName='DuckDuckGo Lite'}
 if(!results.length){const wiki=await provider(`https://en.wikipedia.org/w/api.php?action=opensearch&search=${q}&limit=10&namespace=0&format=json`,html=>{try{const j=JSON.parse(html);return(j[1]||[]).map((title,i)=>({rank:i+1,title,url:(j[3]||[])[i]||'',description:(j[2]||[])[i]||''}))}catch{return[]}});diagnostics.push({provider:'Wikipedia fallback',status:wiki.status,count:wiki.results.length});results=wiki.results;if(results.length)providerName='Wikipedia fallback'}
 return res.status(200).json({ok:true,task,provider:providerName||'No provider',classification:'RESEARCH / FREE LIVE WEB',message:results.length?'Live results returned.':'No provider returned parseable results. See diagnostics for provider status.',diagnostics,stages:[{stage:1,name:'Intent / Intake',status:'completed'},{stage:2,name:'Classification',status:'completed'},{stage:3,name:'Intelligence / Live Web Search',status:results.length?'completed':'empty',result_count:results.length},{stage:4,name:'Evidence',status:results.length?'completed':'empty'},{stage:5,name:'Validation Gate',status:'completed'},{stage:6,name:'Final Gatekeeper',status:'completed'}],results});
}